### 8. Data Handling - Data Cleansing

#### Missing Values

In [1]:
# <데이터가 없을 때 할 수 있는 전략>
# 데이터가 없으면 sample 값 drop
# 데이터가 없는 최소 개수를 정해서 drop ex) 2개 이상 없으면 drop한다.
# 데이터가 거의 없는 feature 자체를 drop
# 최빈값, 평균값으로 비어있는 값 채우기

In [141]:
raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'],
        'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'],
        'age': [42, np.nan, 36, 24, 73],
        'sex': ['m', np.nan, 'f', 'm', 'f'],
        'preTestScore': [4, np.nan, np.nan, 2, 3],
        'postTestScore': [25, np.nan, np.nan, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [142]:
len(df)

5

In [143]:
df.isnull().sum() / len(df)

first_name       0.2
last_name        0.2
age              0.2
sex              0.2
preTestScore     0.4
postTestScore    0.4
dtype: float64

In [144]:
# dropna : NaN있는 행 삭제
df_no_missing = df.dropna()
df_no_missing

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [145]:
df_clean = df.dropna(how='all') # 데이터가 모두 없는 행 날림
df_clean

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [146]:
df['location'] = np.nan
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           NaN            NaN       NaN
2       Tina       Ali  36.0    f           NaN            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [147]:
df.dropna(axis=1, how='all')

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [148]:
df.dropna(axis=0, thresh=5) # 데이터가 5이상은 남아있는 경우

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

In [149]:
df.fillna(0) # nan값을 0으로

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       0.0
1          0         0   0.0   0           0.0            0.0       0.0
2       Tina       Ali  36.0   f           0.0            0.0       0.0
3       Jake    Milner  24.0   m           2.0           62.0       0.0
4        Amy     Cooze  73.0   f           3.0           70.0       0.0

In [150]:
df['preTestScore'].mean()

3.0

In [151]:
df['preTestScore'].median()

3.0

In [152]:
df.mode()

first_name last_name   age  sex  preTestScore  postTestScore  location
0        Amy       Ali  24.0    f           2.0           25.0       NaN
1       Jake     Cooze  36.0    m           3.0           62.0       NaN
2      Jason    Miller  42.0  NaN           4.0           70.0       NaN
3       Tina    Milner  73.0  NaN           NaN            NaN       NaN

In [153]:
df['preTestScore'].fillna(df['preTestScore'].mean(),inplace=True)

In [154]:
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [155]:
df.groupby('sex')['postTestScore'].sum()

sex
f    70.0
m    87.0
Name: postTestScore, dtype: float64

In [164]:
# transform : 그룹별로 값을 계산해서 해당 칼럼의 값에 계산값을 넣음
df.groupby('sex')['postTestScore'].transform('mean')

0    43.5
1     NaN
2    70.0
3    43.5
4    70.0
Name: postTestScore, dtype: float64

In [472]:
df[df['age'].notnull() & df['sex'].notnull()]

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
2       Tina       Ali  36.0   f           3.0            NaN       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

#### Category Data

In [473]:
# One-Hot Encoding

In [474]:
edges = pd.DataFrame({'source': [0, 1, 2],
                   'target': [2, 2, 3],
                       'weight': [3, 4, 5],
                       'color': ['red', 'blue', 'blue']})

edges

source  target  weight color
0       0       2       3   red
1       1       2       4  blue
2       2       3       5  blue

In [475]:
edges.dtypes

source     int64
target     int64
weight     int64
color     object
dtype: object

In [476]:
pd.get_dummies(edges)

source  target  weight  color_blue  color_red
0       0       2       3           0          1
1       1       2       4           1          0
2       2       3       5           1          0

In [477]:
weight_dict = {3:"M", 4:"L", 5:"XL"}
edges["weight_sign"] = edges["weight"].map(weight_dict)
edges

source  target  weight color weight_sign
0       0       2       3   red           M
1       1       2       4  blue           L
2       2       3       5  blue          XL

In [479]:
weight_sign = pd.get_dummies(edges["weight_sign"])
weight_sign

L  M  XL
0  0  1   0
1  1  0   0
2  0  0   1

In [480]:
pd.concat([edges, weight_sign], axis=1)

source  target  weight color weight_sign  L  M  XL
0       0       2       3   red           M  0  1   0
1       1       2       4  blue           L  1  0   0
2       2       3       5  blue          XL  0  0   1

In [481]:
pd.get_dummies(edges).values

array([[0, 2, 3, 0, 1, 0, 1, 0],
       [1, 2, 4, 1, 0, 1, 0, 0],
       [2, 3, 5, 1, 0, 0, 0, 1]])

In [482]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [483]:
bins = [0, 25, 50, 75, 100] # Define bins as 0 to 25, 25 to 50, 60 to 75, 75 to 100
group_names = ['Low', 'Okay', 'Good', 'Great']
categories = pd.cut(df['postTestScore'], bins, labels=group_names)
categories

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [484]:
df['categories'] = pd.cut(df['postTestScore'], bins, labels=group_names)
pd.value_counts(df['categories'])

Good     8
Great    2
Low      2
Okay     0
Name: categories, dtype: int64

In [485]:
pd.get_dummies(df)

preTestScore  postTestScore  regiment_Dragoons  regiment_Nighthawks  \
0              4             25                  0                    1   
1             24             94                  0                    1   
2             31             57                  0                    1   
3              2             62                  0                    1   
4              3             70                  1                    0   
5              4             25                  1                    0   
6             24             94                  1                    0   
7             31             57                  1                    0   
8              2             62                  0                    0   
9              3             70                  0                    0   
10             2             62                  0                    0   
11             3             70                  0                    0   

    regiment_Scouts  company_1st  company_2nd  name_Ali  name_Cooze  \
0                 0            1            0         0           0   
1                 0            1            0         0           0   
2                 0            0            1         1           0   
3                 0            0            1         0           0   
4                 0            1            0         0           1   
5                 0            1            0         0           0   
6                 0            0            1         0           0   
7                 0            0            1         0           0   
8                 1            1            0         0           0   
9                 1            1            0         0           0   
10                1            0            1         0           0   
11                1            0            1         1           0   

    name_Jacobson  ...  name_Milner  name_Piger  name_Riani  name_Ryaner  \
0               0  ...            0           0           0            0   
1               1  ...            0           0           0            0   
2               0  ...            0           0           0            0   
3               0  ...            1           0           0            0   
4               0  ...            0           0           0            0   
5               0  ...            0           0           0            0   
6               0  ...            0           0           0            1   
7               0  ...            0           0           0            0   
8               0  ...            0           0           0            0   
9               0  ...            0           1           0            0   
10              0  ...            0           0           1            0   
11              0  ...            0           0           0            0   

    name_Sloan  name_Sone  categories_Low  categories_Okay  categories_Good  \
0            0          0               1                0                0   
1            0          0               0                0                0   
2            0          0               0                0                1   
3            0          0               0                0                1   
4            0          0               0                0                1   
5            0          0               1                0                0   
6            0          0               0                0                0   
7            0          1               0                0                1   
8            1          0               0                0                1   
9            0          0               0                0                1   
10           0          0               0                0                1   
11           0          0               0                0                1   

    categories_Great  
0                  0  
1                  1  
2                 

In [486]:
# using scikit-learn preprocessing

In [494]:
raw_example = df.as_matrix()
raw_example[:3]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([['Nighthawks', '1st', 'Miller', 4, 25, 'Low'],
       ['Nighthawks', '1st', 'Jacobson', 24, 94, 'Great'],
       ['Nighthawks', '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

In [495]:
data = raw_example.copy()

In [497]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [491]:
raw_example[:,0]

array(['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons',
       'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts',
       'Scouts'], dtype=object)

In [498]:
le.fit(raw_example[:,0])

LabelEncoder()

In [499]:
le.classes_

array(['Dragoons', 'Nighthawks', 'Scouts'], dtype=object)

In [500]:
le.transform(raw_example[:,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [502]:
data[:,0] = le.transform(raw_example[:,0])
data[:3]

array([[1, '1st', 'Miller', 4, 25, 'Low'],
       [1, '1st', 'Jacobson', 24, 94, 'Great'],
       [1, '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

In [503]:
label_column = [0,1,2,5]
label_enconder_list = []
for column_index in  label_column:
    le = preprocessing.LabelEncoder()
    le.fit(raw_example[:,column_index])
    data[:,column_index] = le.transform(raw_example[:,column_index])
    label_enconder_list.append(le)
    del le 
data[:3]

array([[1, 0, 4, 4, 25, 2],
       [1, 0, 2, 24, 94, 1],
       [1, 1, 0, 31, 57, 0]], dtype=object)

In [504]:
label_enconder_list[0].transform(raw_example[:10,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2])

In [505]:
one_hot_enc = preprocessing.OneHotEncoder()
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [506]:
one_hot_enc.fit(data[:,0].reshape(-1,1))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [509]:
onehotlabels = one_hot_enc.transform(data[:,0].reshape(-1,1)).toarray()
onehotlabels

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

### 9. Data Handling - Kaggle

In [1]:
# kaggle site에서 다른 사람 EDA는 참고할 것. 데이터 전처리

In [2]:
# Titanic: Machine Learning from Disaster

In [3]:
# House Prices: Advanced Regression Techniques